"""Go-bot Python 插件 SDK。

这个包的目标是给 IDE 提供稳定的类型入口。
运行时如果宿主已经注入 gobot_runtime，则会直接复用真实运行时实现。
"""

from .models import (
    AppInfo,
    BotStatus,
    ForwardMessage,
    ForwardNode,
    GroupInfo,
    GroupMemberInfo,
    LoginInfo,
    MessageDetail,
    MessageEvent,
    MessageSegment,
    MessageTarget,
    PluginInfo,
    PluginManifest,
    ResolvedMedia,
    UserInfo,
)
from .runtime import (
    AIToolContext,
    AIToolDefinition,
    AIToolRegistrar,
    BasePlugin,
    BotAPI,
    ForwardOptions,
    Logger,
    Messenger,
    PluginCatalog,
    PluginEnv,
    RuntimeErrorResponse,
    at_segment,
    build_target,
    clone_segment,
    file_segment,
    image_segment,
    music_custom_segment,
    parse_event_timestamp,
    run_plugin,
    segment_text,
    text_node,
    text_segment,
    video_segment,
)

__all__ = [
    "AppInfo",
    "AIToolContext",
    "AIToolDefinition",
    "AIToolRegistrar",
    "BasePlugin",
    "BotAPI",
    "BotStatus",
    "ForwardMessage",
    "ForwardNode",
    "ForwardOptions",
    "GroupInfo",
    "GroupMemberInfo",
    "Logger",
    "LoginInfo",
    "MessageDetail",
    "MessageEvent",
    "MessageSegment",
    "MessageTarget",
    "Messenger",
    "PluginCatalog",
    "PluginEnv",
    "PluginInfo",
    "PluginManifest",
    "ResolvedMedia",
    "RuntimeErrorResponse",
    "UserInfo",
    "at_segment",
    "build_target",
    "clone_segment",
    "file_segment",
    "image_segment",
    "music_custom_segment",
    "parse_event_timestamp",
    "run_plugin",
    "segment_text",
    "text_node",
    "text_segment",
    "video_segment",
]
