server:
  host: 0.0.0.0
  port: 8080
bot:
  nickname: "罗纸酱"
  master: 
  function:
    test: false
    video_parser: false
    forging_message: false
    phantom_tank: false
    jmcomic_download: false
    freqtrade:
      enabled: true
      api_url:
      username:
      password:
video_parser:
  video_max_size: 50