server:
  host: 0.0.0.0
  port: 8080
bot:
  nickname: "罗纸酱"
  function:
    test: false
    video_parser: true
    forging_message: true
    phantom_tank: true
    jmcomic_download: true
video_parser:
  video_max_size: 50